#======================================================#
# 2019 (C) ItsMeAcktar Productions
# 2019 (C) SavageSB Network
# 2019 (C) UltimateSpeak Server Systems
#======================================================#
name: PremiumBW
version: 1.0.0
api: [3.5.8, 3.5.7, 3.5.6, 3.5.5, 3.5.9, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.6.5]
main: PremiumBW\ItsMeAcktar
author: ItsMeAcktar
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
